'use client';


import { Inter } from "next/font/google";
import "./ui/globals.css";
import { Provider } from 'react-redux';
import store from "../app/store/store"

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Provider store={store}>


        <body className={inter.className}>
          {children}
        </body>

      </Provider>

    </html>


  );
}


RootLayout.metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};